//Q2. Create a class Account having private instance member Id, Name Balanceamt. Id should be generated by application. Create method deposit who’s job is to increase Balanceamtby the amout deposited by account holder. Create method withdraw who’s job is to decrease Balanceamt by the amount  withdrawn by account holder. Write method display which will display name and Balanceamt. Your application should generate only 3 object, if you try to generate 4 th object it should display message can not create object. This application will be classlibrary.
//Create console application and use this class library. Create at least two object of account class and deposit and withdraw money.

using System;
using Acc_Lib;

namespace Q2_Account_Validation
{
    class Program
    {
        static Program ()                    //static constructor loads the name of bank as soon as application loads.
            {
                Console.WriteLine("\n-----------------------------------------------------------------------------------------------------");
                Console.WriteLine("\n*************************************** Bank Of Unknown *********************************************\n");
                Console.WriteLine("-------------------------------------------------------------------------------------------------------\n");
            }

            static Account create_acc()         //account creation
            {
                Account a = null;          
                try                             //using try catch block to keepp a tab if 4th account is being made it will throw an exception.
                {
                    Console.Write("Enter Your Name : ");
                    string n1 = Console.ReadLine();
                    a = new Account(n1);
                    a.disp();
                }
                catch (Exception )
                {
                Console.WriteLine("\nMaximim number of accounts reached!Cant make more accounts.");
                }
                return a;
            }

        static void deposit(Account a)      //deposit method
        {
            double amt;
            Console.Write("Enter amount to be deposited in acoount : ");
            if (double.TryParse(Console.ReadLine(), out amt))
                a.Deposit(amt);                     //calls the library and updates the balance & displays the new balance in display
            else
            {
                Console.WriteLine("Invalid Input! Amount Should Be Numeric Only.");
                deposit(a);
            }
        }

        static void withdraw(Account a)         //withdraw method
        {
            double amt;
            Console.Write("Enter Amount to be withdraw from account : ");
            if (double.TryParse(Console.ReadLine(), out amt))
                a.Withdraw(amt);                //calls the lib and decrements the balance & displays new balance.
            else 
            {
                Console.WriteLine("Invalid Input! Amount Should Be Numeric Only.");
                withdraw(a);
            }

        }
    

        static void Main(string[] args)
        {
            Account a1 = create_acc();
            Account a2 = create_acc();
            Account a3 = create_acc();
            Account a4 = create_acc();

            int ch=0;
            do {
                
                Console.WriteLine("\nEnter Choice Of Operation(2 Object Of Account Class)  : ");
                Console.WriteLine("\n1.Deposit in Account 1\n2.Withdraw from Account 1\n3.Deposit in Account 2\n4.Withdraw from Account 2\n5.Exit\n");
                if (!(int.TryParse(Console.ReadLine(), out ch)))
                    ch = 6;
                switch (ch) {
                    case 1:
                        deposit(a1);
                        break;
                    case 2:
                        withdraw(a1);
                        break;
                    case 3:
                        deposit(a2);
                        break;
                    case 4:
                        withdraw(a2);
                        break;
                    case 5:
                        Console.WriteLine("Exit the Application.....");
                        break;
                    default:
                        Console.WriteLine("Invalid choice Select from 1 to 5 only.");
                        break;
                }
            } while (ch != 5);
        
        }
    }
}
