/*Create a class Employee having private instance member 
id- id is readonly property and generated by your application
name- write getter setter
salary- write getter setter
net salary
Write method who’s job is to deduct TDS 10% and return tax amount and set netsalary instance member after deducting tax.
Declare TDS as static variable.
Your application should create only 3 object if you try to create 4th object it should throw exception.
Give appropriate validation like salary can not be 0 or negative, maximum
Salary allowed is 50000 if you try to set more then 50000 it should give some error message.
When you run your application it should print name of company.*/

//hardcoded values for these one as employee & Account class is continued further days

using System;
using Emp_Lib;

namespace _1_Employee_Getter_Setter
{
    class Program
    {
        static Program()
        {
            Console.WriteLine("-------------------------------------------------------");
            Console.WriteLine("\n\t**********Corporation Of Employee**********\n");
            Console.WriteLine("-------------------------------------------------------");
        }
    

        static void Main(string[] args)
        {
            try 
            {
                Employee e1 = new Employee("mitsu", 49999);
                e1.tds_calc();
                Console.WriteLine("\nID: {0} Name: {1} Netsalary: {2}", e1.ID, e1.Name, e1.Net);

                Employee e2 = new Employee("jerry", 25000);        //invalid salary
                e2.tds_calc();
                Console.WriteLine("\nID: {0} Name: {1} Netsalary: {2}", e2.ID, e2.Name, e2.Net);
                
               /*Employee e3 = new Employee("vishal", 100000);
                e3.tds_calc();
                Console.WriteLine("\nID: {0} Name: {1} Netsalary: {2}", e3.ID, e3.Name, e3.Net);*/

                Employee e4 = new Employee("shubham", 10000);                 
                e4.tds_calc();
                Console.WriteLine("\nID: {0} Name: {1} Netsalary: {2}", e4.ID, e4.Name, e4.Net);


                Employee e5 = new Employee("unknown", 0);              //Max Object creation limit reached.
            }
            catch
            {
                Console.WriteLine("\nPlease Enter Valid Salary Credentials.Salary Can't Be Zero OR More Than 50000,Employee Object Cant Be Created.");
            }

            Console.ReadLine();
        }
    }
}
