//Q3. Create a class Employee having private instance member Id, Name Salary, netsalary.  Id should be generated by application Create method calculate_netsalary who’s job is to deduct 10% of TDS. Declare TDS as static variable. Write method display which will display name and netsalary. This application will be classlibrary. Declare const int maxemp=3 ie. You can have only 3 employee.
//Also declare const int maxsal=50000. Use this for validation in constructor if you try to create object with salary 80000 it should display error
//Create console application and use this class library. Create at least two object of Employee class.

using System;
using EmpSal_lib;

namespace Q3_Employee_Salary
{
    class Program
    {
        static Program()
        {
            Console.WriteLine("\n-----------------------------------------------------------------------------------------------------");
            Console.WriteLine("\n*************************************** Corporation Of Employeees *********************************************\n");
            Console.WriteLine("-------------------------------------------------------------------------------------------------------\n");
        }

        static Employee createEmp()
        {

            Employee e1 = null;
            Console.Write("Enter name of employee : ");
            string name = Console.ReadLine();
            Console.Write("\nEnter Salary of " + name + ":");
            double sal;
            if (!(double.TryParse(Console.ReadLine(), out sal)))
            {
                Console.WriteLine("Salary Should Be Numeric Values Only.");
                createEmp();
            }
            try
            {
                e1 = new Employee(name, sal);
            }
            catch (Max_Emp)
            {
                Console.WriteLine("\n*********************************************************");
                Console.WriteLine("Maximum No Of employee Record reached.Cant Create More Object.");
                Console.WriteLine("*********************************************************\n");
                return null;
            }
            catch (Max_Sal)
            {
                Console.WriteLine("\n*********************************************************");
                Console.WriteLine("Maximum salary exceeded!!!Salary For employee Should Not Exceed 80000 ,Please enter Valid Input.");
                Console.WriteLine("*********************************************************\n");
                Employee.decid();
                e1 = createEmp();
            }

            return e1;
        }
        
        static void Main(string[] args)
        {
            Employee e1 = createEmp();
            Console.WriteLine("\n");
            Employee e2 = createEmp();
            Console.WriteLine("\n");
            Employee e3 = createEmp();
            Console.WriteLine("\n");
            Employee e4 = createEmp();
            Console.WriteLine("\nHit Enter To Display The Salary Records Of Employee.");
            Console.ReadLine();
            Console.WriteLine("\n------------------------------Details Of Salary Of Employee---------------------------------------\n");
            e1.disp();
            e2.disp();
            e3.disp();
            Console.ReadLine();

        }
    }
}
